# Generated by Django 5.1.3 on 2024-11-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_players_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='passwd',
            field=models.CharField(max_length=128),
        ),
    ]
