# Generated by Django 5.1.3 on 2024-11-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_player_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(default='default@default.com', max_length=80),
        ),
        migrations.AlterField(
            model_name='player',
            name='fname',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='player',
            name='lname',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='player',
            name='passwd',
            field=models.CharField(default='', max_length=128),
        ),
    ]
