# Generated by Django 5.1.3 on 2024-11-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_player_email_alter_player_fname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='player_pictures/'),
        ),
    ]
