# Generated by Django 5.1.3 on 2024-11-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_player_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
