# Generated by Django 5.1.3 on 2024-11-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_player_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='picture',
            field=models.URLField(blank=True, default='https://example.com/default-profile.jpg', null=True),
        ),
    ]
