# Generated by Django 5.1.4 on 2024-12-09 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_player_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
    ]
