# Generated by Django 5.1.3 on 2024-12-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_friendrequest_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='language',
            field=models.CharField(default='English', max_length=30),
        ),
    ]
