# Generated by Django 5.1.4 on 2024-12-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_player_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='two_factor',
            field=models.BooleanField(default=False),
        ),
    ]
