# Generated by Django 5.1.4 on 2025-01-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_player_two_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='loss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='nb_games',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='rb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='tr_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
