# Generated by Django 5.1.5 on 2025-01-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_player_loss_player_nb_games_player_rb_player_tr_wins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='mfa_secret',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
