# Generated by Django 5.1.5 on 2025-02-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_blockeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
