# Generated by Django 5.1.5 on 2025-01-26 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_userstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserStatus',
        ),
    ]
