# Generated by Django 5.1.5 on 2025-02-13 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_player_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('win', models.BooleanField()),
                ('opponent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.player')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_results', to='users.player')),
            ],
        ),
    ]
