# Generated by Django 5.1.6 on 2025-02-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_gameresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='language',
            field=models.CharField(default='English', max_length=30),
        ),
    ]
